config/routes.rb
FriendCircle::Application.routes.draw do
  resources :users do
    collection do
      get 'forgot_password'
      post 'email_password_reset'
      get 'password_reset'
      get 'feed'
    end
  end

  resource :session
  resources :circles
  resources :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  attr_reader :password

  has_many(
    :circles,
    class_name: "Circle",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :memberships,
    class_name: "CircleMembership",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy,
    inverse_of: :author
  )

  has_many(
    :circles_user_belongs_to,
    through: :memberships,
    source: :circle
  )

  has_many(
    :feed_posts,
    through: :circles_user_belongs_to,
    source: :posts_shared_with_a_circle
  )

  before_validation :ensure_session_token
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  def self.find_by_credentials(email, secret)
    user = User.find_by_email(email)
    return nil if user.nil?

    user.is_password?(secret) ? user : nil
  end

  def password=(secret)
    self.password_digest = BCrypt::Password.create(secret)
  end

  def is_password?(secret)
    BCrypt::Password.new(password_digest).is_password?(secret)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_logged_in,
    only: [:new, :create, :forgot_password, :password_reset, :email_password_reset]
  before_filter :require_logged_out,
    only: [:new, :create, :forgot_password, :password_reset, :email_password_reset]

  def new
    render :new
  end

  def create
    @user = User.new(params[:user])
    @post = @user.posts.new(params[:post])
    @urls = params[:links].values.select { |hsh| hsh["url"].length > 0 }
    @post.links.new(@urls)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = "Invalid email or password."
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])

    render :show
  end

  def forgot_password
    render :forgot_password
  end

  def email_password_reset
    user = User.find_by_email(params[:email])
    msg = UserMailer.forgot_password_email(user)
    msg.deliver!
  end

  def password_reset
    user = User.find_by_session_token(params[:q])
    @new_password = SecureRandom.urlsafe_base64(6)
    user.password = @new_password
    user.save

    render :password_reset
  end

  def feed
    @posts = current_user.feed_posts
    render :feed
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/feed.html.erb
<ul>
<% @posts.each do |post| %>
<li>
  <%= link_to post.title, post_url(post)%> by <%= post.author.email %>
</li>
<% end %>
</ul>

app/views/users/forgot_password.html.erb
Enter your email to reset your password:
<br>
<form action="<%= email_password_reset_users_url %>"
  method="POST">

  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >
  <label for="email">Email:</label>
  <input type="text" id="email" name="email">
  <br>
  <input type="submit" name="Reset Password">
</form>

app/views/users/new.html.erb
<h1>Sign up for Friend Circle</h1>

<form action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >

  <label for="user_email">Email</label>
  <input type="text" id="user_email" name="user[email]">

  <label for="user_password">Password</label>
  <input type="password" id="user_password" name="user[password]">

  <label for="post_title">Title</label>
  <input
    type="text"
    id="post_title"
    name="post[title]">
  <br>
  <label for="post_body">Body</label>
  <input
    type="textarea"
    col="40"
    row="40"
    id="post_body"
    name="post[body]">
  <br>
  <label>Links
  <% 3.times do |i| %>
    <input
      type="text"
      name="links[<%= i %>][url]">
  <% end %>
  </label>

  <input type="submit" value="Sign Up">
</form>

app/views/users/password_reset.html.erb
Your new password is <%= @new_password %>.

app/views/users/show.html.erb
<h3><%= @user.email %></h3>