config/routes.rb
FriendCircle::Application.routes.draw do
  resources :users do
    collection do
      get 'forgot_password'
      post 'email_password_reset'
      get 'password_reset'
      get 'feed'
    end
  end

  resource :session
  resources :circles
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :user_id, :body, :title

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :posts
  )

  has_many(
    :links,
    class_name: "Link",
    foreign_key: :post_id,
    primary_key: :id,
    dependent: :destroy,
    inverse_of: :post
  )

  has_many(
    :post_shares,
    class_name: "PostShare",
    foreign_key: :post_id,
    primary_key: :id,
    dependent: :destroy,
    inverse_of: :post
  )

  has_many :circles, through: :post_shares, source: :circle

  validates :author, :body, :title, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @links = @post.links
    render :show
  end

  def index
    @posts = Post.all
    render :index
  end

  def new
    @post = Post.new
    # 3.times { @post.links.new }
    @urls = ["","",""]
    render :new
  end

  def create
    params[:post][:user_id] = current_user.id
    @post = Post.new(params[:post])
    @post.post_shares.new(params[:circle_shares].values)
    @urls = params[:links].values.select { |hsh| hsh["url"].length > 0 }
    @post.links.new(@urls)

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = "Your post wasn't created."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @urls = @post.links.map { |link| link.url }
    render :edit
  end

  def destroy
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% action_url = (action == :new ? posts_url : post_url(post))%>
<% action_method = (action == :new ? "post" : "put")%>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= action_method %>">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >

  <label for="post_title">Title</label>
  <input
    type="text"
    id="post_title"
    name="post[title]"
    value="<%= post.title %>">
  <br>
  <label for="post_body">Body</label>
  <input
    type="textarea"
    col="40"
    row="40"
    id="post_body"
    name="post[body]"
    value="<%= post.body %>">
  <br>
  <% current_user.circles.each_with_index do |circle, i| %>
    <label>
      <%= circle.name %>
      <input
        type="checkbox"
        value="<%= circle.id %>"
        name="circle_shares[<%= i %>][circle_id]"
        <%= post.circles.include?(circle) ? "checked" : "" %>>
    </label>
  <% end %>
  <br>
  <label>Links
  <% 3.times do |i| %>
    <input
      type="text"
      name="links[<%= i %>][url]"
      value="<%= urls.pop %>">
  <% end %>
  </label>
  <input type="submit" value="Create Post">
</form>

app/views/posts/edit.html.erb
<%= render 'form', post: @post, urls: @urls, action: :edit %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% @posts.each do |post| %>
  <%= link_to post.title, post_url(post) %>
<% end %>

app/views/posts/new.html.erb
<%= render "form", post: @post, urls: @urls, action: :new %>

app/views/posts/show.html.erb
<p><%= @post.body %></p>

<% @links.each do |link| %>
  <%= link_to link.url, link.url %>
<% end %>