config/routes.rb
FriendCircle::Application.routes.draw do
  resources :users do
    collection do
      get 'forgot_password'
      post 'email_password_reset'
      get 'password_reset'
      get 'feed'
    end
  end

  resource :session
  resources :circles
  resources :posts
end

app/models/circle.rb
class Circle < ActiveRecord::Base
  attr_accessible :user_id, :name, :member_ids

  has_many(
    :memberships,
    class_name: "CircleMembership",
    foreign_key: :circle_id,
    primary_key: :id,
    inverse_of: :circle,
    dependent: :destroy
  )

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :post_shares,
    class_name: "PostShare",
    foreign_key: :circle_id,
    primary_key: :id,
    dependent: :destroy,
  )

  has_many(
    :posts_shared_with_a_circle,
    through: :post_shares,
    source: :post
  )

  has_many :members, through: :memberships, source: :member

  validates :user_id, :name, presence: true

end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController

  def index
    @circles = Circle.all

    render :index
  end

  def show
    @circle = Circle.find(params[:id])
    @members = @circle.members

    render :show
  end

  def new
    @circle = Circle.new
    render :new
  end

  def create
    params[:circle][:user_id] = current_user.id
    circle = Circle.new(params[:circle])

    if circle.save
      redirect_to circle_url(circle)
    else
      flash.now[:errors] = "Your circle wasn't created."
      render :new
    end
  end

  def edit
    @circle = Circle.find(params[:id])
  end

  def update
    @circle = Circle.find(params[:id])
    if @circle.update_attributes(params[:circle])
      redirect_to circle_url(@circle)
    else
      flash.now[:errors] = "Your circle wasn't updated."
      render :edit
    end
  end

  def destroy
    circle = Circle.find(params[:id])
    if current_user == circle.owner
      circle.destroy
    else
      flash.now[:errors] = "Can't delete circles you didn't create"
    end
    redirect_to user_url(current_user)
  end

end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<% action_url = (action == :new ? circles_url : circle_url(@circle)) %>
<% method = (action == :new ? "post" : "put") %>

<form action="<%= action_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="circle_name">Circle Name</label>
  <input type="text"
    id="circle_name"
    name="circle[name]"
    value="<%= @circle.name %>"
  >

  <input type="hidden" name="circle[member_ids][]" value="">
  <% User.all.each do |user| %>
    <label>
      <%= user.email %>
      <input type="checkbox" name="circle[member_ids][]" value="<%= user.id %>" <%= @circle.members.include?(user) ? "checked" : "" %>>
    </label>
  <% end %>

  <input type="submit" value="Submit">
</form>

app/views/circles/edit.html.erb
<h1>Edit a circle</h1>
<%= render 'form', action: :edit %>

app/views/circles/new.html.erb
<h1>Create a new circle</h1>
<%= render 'form', action: :new %>

app/views/circles/show.html.erb
<%= @circle.name %>
<br>
<% @circle.members.each do |member| %>
  <%= member.email %><br>
<% end %>